"""
Report generation service for comprehensive analytics and export.

Generates detailed fitness reports including:
- Historical metrics (calories, macros, weight, BMI)
- Food analysis (frequency, problematic foods)
- Goal progress and pace
- Trend analysis
- Actionable suggestions
- Export formats (JSON, HTML, PDF, email)
"""

from datetime import date, datetime, timedelta
import json
import logging
from typing import Optional
from sqlalchemy.orm import Session

from app.models import User, UserGoal, WeightLog, FoodLog
from app.services.aggregation import (
    get_logging_stats,
    get_average_metrics,
    get_best_worst_days,
    get_food_frequency,
    get_weight_trend,
    calculate_consistency_score,
)
from app.services.food_quality import get_problematic_foods
from app.services.suggestions import get_suggestions

logger = logging.getLogger(__name__)

# Report availability threshold
MIN_LOGGING_DAYS = 7


class Report:
    """Comprehensive fitness report."""

    def __init__(self, user_id: int, period_start: date, period_end: date):
        """
        Args:
            user_id: User ID
            period_start: Report start date
            period_end: Report end date
        """
        self.user_id = user_id
        self.period_start = period_start
        self.period_end = period_end
        self.generated_at = datetime.utcnow()

        # Report sections
        self.summary = {}
        self.metrics = {}
        self.food_analysis = {}
        self.goal_progress = {}
        self.trends = {}
        self.suggestions = []
        self.metadata = {}

    def to_dict(self) -> dict:
        """Convert report to dictionary for JSON serialization."""
        return {
            "user_id": self.user_id,
            "period": {
                "start": self.period_start.isoformat(),
                "end": self.period_end.isoformat(),
            },
            "generated_at": self.generated_at.isoformat(),
            "summary": self.summary,
            "metrics": self.metrics,
            "food_analysis": self.food_analysis,
            "goal_progress": self.goal_progress,
            "trends": self.trends,
            "suggestions": [s.to_dict() for s in self.suggestions],
            "metadata": self.metadata,
        }

    def to_html(self) -> str:
        """Generate HTML representation of report."""
        html = f"""
        <html>
        <head>
            <meta charset="UTF-8">
            <title>FitTrack Report - {self.period_start} to {self.period_end}</title>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; color: #333; }}
                h1 {{ color: #2c3e50; border-bottom: 3px solid #3498db; padding-bottom: 10px; }}
                h2 {{ color: #34495e; margin-top: 30px; border-left: 4px solid #3498db; padding-left: 10px; }}
                h3 {{ color: #7f8c8d; }}
                .metric {{ display: inline-block; margin: 10px 20px 10px 0; }}
                .metric-value {{ font-size: 24px; font-weight: bold; color: #3498db; }}
                .metric-label {{ color: #7f8c8d; font-size: 12px; text-transform: uppercase; }}
                .warning {{ background-color: #fff3cd; padding: 10px; border-left: 4px solid #ffc107; margin: 10px 0; }}
                .success {{ background-color: #d4edda; padding: 10px; border-left: 4px solid #28a745; margin: 10px 0; }}
                table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
                th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
                th {{ background-color: #ecf0f1; font-weight: bold; }}
                .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #7f8c8d; font-size: 12px; }}
            </style>
        </head>
        <body>
            <h1>FitTrack Report</h1>
            <p><strong>Period:</strong> {self.period_start} to {self.period_end}</p>
            <p><strong>Generated:</strong> {self.generated_at.strftime('%Y-%m-%d %H:%M:%S')}</p>

            <h2>Summary</h2>
            {self._html_summary()}

            <h2>Metrics</h2>
            {self._html_metrics()}

            <h2>Food Analysis</h2>
            {self._html_food_analysis()}

            <h2>Goal Progress</h2>
            {self._html_goal_progress()}

            <h2>Trends</h2>
            {self._html_trends()}

            <h2>Suggestions</h2>
            {self._html_suggestions()}

            <div class="footer">
                <p>This report is generated by FitTrack on {self.generated_at.strftime('%Y-%m-%d')}.</p>
            </div>
        </body>
        </html>
        """
        return html

    def _html_summary(self) -> str:
        """Generate HTML for summary section."""
        html = '<div class="summary">'
        for key, value in self.summary.items():
            if isinstance(value, (int, float)):
                html += f"""
                <div class="metric">
                    <div class="metric-value">{value:.1f if isinstance(value, float) else value}</div>
                    <div class="metric-label">{key.replace('_', ' ').title()}</div>
                </div>
                """
            else:
                html += f'<p><strong>{key}:</strong> {value}</p>'
        html += '</div>'
        return html

    def _html_metrics(self) -> str:
        """Generate HTML for metrics section."""
        html = '<table><tr><th>Metric</th><th>Value</th></tr>'
        for key, value in self.metrics.items():
            if isinstance(value, (int, float)):
                html += f'<tr><td>{key.replace("_", " ").title()}</td><td>{value:.1f if isinstance(value, float) else value}</td></tr>'
            else:
                html += f'<tr><td>{key.replace("_", " ").title()}</td><td>{value}</td></tr>'
        html += '</table>'
        return html

    def _html_food_analysis(self) -> str:
        """Generate HTML for food analysis section."""
        if not self.food_analysis:
            return '<p>No food analysis available.</p>'

        html = '<h3>Frequent Foods</h3>'
        if "frequent_foods" in self.food_analysis:
            html += '<table><tr><th>Food</th><th>Count</th><th>Category</th></tr>'
            for food in self.food_analysis.get("frequent_foods", [])[:5]:
                html += f'<tr><td>{food.get("food_text")}</td><td>{food.get("count")}</td><td>{food.get("category")}</td></tr>'
            html += '</table>'

        html += '<h3>Problematic Foods</h3>'
        problematic = self.food_analysis.get("problematic_foods", [])
        if problematic:
            for food in problematic[:5]:
                html += f"""
                <div class="warning">
                    <strong>{food.get("food_text")}</strong> (Quality: {food.get("quality_score")}/100)
                    <br>Logged {food.get("frequency")} times | Impact: {food.get("impact_rating").upper()}
                    <br>Concerns: {', '.join(food.get("concerns", []))}
                </div>
                """
        else:
            html += '<p>No problematic foods identified.</p>'

        return html

    def _html_goal_progress(self) -> str:
        """Generate HTML for goal progress section."""
        if not self.goal_progress:
            return '<p>No goal set.</p>'

        progress = self.goal_progress
        html = f"""
        <p><strong>Goal:</strong> Reach {progress.get('target_weight')}kg by {progress.get('target_date')}</p>
        <p><strong>Current Weight:</strong> {progress.get('current_weight')}kg</p>
        <p><strong>Progress:</strong> {progress.get('weight_lost')}kg lost so far</p>
        <p><strong>Pace:</strong> {progress.get('pace_per_week'):.2f}kg/week (target: {progress.get('target_pace_per_week'):.2f}kg/week)</p>
        """

        if progress.get("on_track"):
            html += '<div class="success"><strong>On Track!</strong> Your current pace aligns with your goal deadline.</div>'
        else:
            html += '<div class="warning"><strong>Off Track.</strong> Your pace suggests you may need to adjust your goal or timeline.</div>'

        return html

    def _html_trends(self) -> str:
        """Generate HTML for trends section."""
        if not self.trends:
            return '<p>Not enough data for trend analysis.</p>'

        trend = self.trends
        html = f"""
        <p><strong>Weight Trend:</strong> {trend.get('trend', 'unknown').upper()}</p>
        <p><strong>Slope:</strong> {trend.get('slope', 0):.2f}kg/week</p>
        <p><strong>Variance:</strong> {trend.get('variance', 0):.2f}</p>
        <p><strong>Insight:</strong> {trend.get('insight', 'No insight available.')}</p>
        """
        return html

    def _html_suggestions(self) -> str:
        """Generate HTML for suggestions section."""
        if not self.suggestions:
            return '<p>No suggestions available.</p>'

        html = ''
        priority_colors = {"high": "warning", "medium": "default", "low": "default"}

        for suggestion in self.suggestions[:10]:  # Top 10 suggestions
            color_class = priority_colors.get(suggestion.priority, "default")
            html += f"""
            <div class="{color_class}">
                <strong>{suggestion.title}</strong> <em>({suggestion.priority.upper()} priority)</em>
                <p>{suggestion.description}</p>
            </div>
            """

        return html


def generate_report(
    db: Session,
    user_id: int,
    days: int = 30,
) -> Optional[Report]:
    """
    Generate comprehensive fitness report for user.

    Requires minimum logging activity (7+ days) to be valid.

    Args:
        db: Database session
        user_id: User ID
        days: Lookback period in days (default 30)

    Returns:
        Report object, or None if insufficient data
    """
    user = db.query(User).filter(User.id == user_id).first()
    if not user:
        return None

    end_date = date.today()
    start_date = end_date - timedelta(days=days)

    # Check if sufficient logging data exists
    stats = get_logging_stats(db, user_id, start_date, end_date)
    if stats.get("total_days_logged", 0) < MIN_LOGGING_DAYS:
        logger.warning(f"Insufficient data for report: {stats.get('total_days_logged')} days logged")
        return None

    # Create report
    report = Report(user_id, start_date, end_date)

    # Populate sections
    report.summary = _build_summary(db, user, stats, start_date, end_date)
    report.metrics = _build_metrics(db, user_id, start_date, end_date)
    report.food_analysis = _build_food_analysis(db, user_id, start_date, end_date)
    report.goal_progress = _build_goal_progress(db, user_id)
    report.trends = _build_trends(db, user_id, days)
    report.suggestions = get_suggestions(db, user_id, days, use_ai=True)
    report.metadata = {
        "data_source": "FitTrack",
        "report_version": "1.0",
    }

    return report


def _build_summary(db: Session, user: User, stats: dict, start_date: date, end_date: date) -> dict:
    """Build summary section of report."""
    consistency = calculate_consistency_score(db, user.id, start_date, end_date)
    metrics = get_average_metrics(db, user.id, start_date, end_date)

    return {
        "user_name": user.email,
        "report_period_days": (end_date - start_date).days,
        "days_logged": stats.get("total_days_logged", 0),
        "consistency_score": consistency,
        "max_streak": stats.get("max_streak", 0),
        "avg_daily_calories": metrics.get("avg_calories", 0),
        "avg_daily_protein": metrics.get("avg_protein", 0),
    }


def _build_metrics(db: Session, user_id: int, start_date: date, end_date: date) -> dict:
    """Build metrics section of report."""
    metrics = get_average_metrics(db, user_id, start_date, end_date)

    return {
        "avg_calories": metrics.get("avg_calories", 0),
        "avg_protein": metrics.get("avg_protein", 0),
        "avg_carbs": metrics.get("avg_carbs", 0),
        "avg_fat": metrics.get("avg_fat", 0),
        "avg_weight": metrics.get("avg_weight"),
        "avg_bmi": metrics.get("avg_bmi"),
        "days_with_food_logs": metrics.get("days_with_food_logs", 0),
        "days_with_weight_logs": metrics.get("days_with_weight_logs", 0),
    }


def _build_food_analysis(db: Session, user_id: int, start_date: date, end_date: date) -> dict:
    """Build food analysis section of report."""
    frequent_foods = get_food_frequency(db, user_id, start_date, end_date, top_n=10)
    problematic_foods = get_problematic_foods(db, user_id, start_date, end_date, threshold=40, limit=5)

    return {
        "frequent_foods": frequent_foods,
        "problematic_foods": problematic_foods,
    }


def _build_goal_progress(db: Session, user_id: int) -> dict:
    """Build goal progress section of report."""
    goal = db.query(UserGoal).filter(UserGoal.user_id == user_id).first()
    if not goal:
        return {}

    # Get current weight
    latest_weight = db.query(WeightLog).filter(
        WeightLog.user_id == user_id,
    ).order_by(WeightLog.date.desc()).first()

    if not latest_weight:
        return {}

    current_weight = latest_weight.weight
    weight_lost = current_weight - goal.weight_target
    days_remaining = (goal.target_date.date() - date.today()).days

    if days_remaining <= 0:
        pace_per_week = 0
        target_pace_per_week = 0
        on_track = False
    else:
        weight_to_lose = max(0, current_weight - goal.weight_target)
        target_pace_per_week = goal.weekly_loss_rate or (weight_to_lose / (days_remaining / 7)) if days_remaining > 0 else 0
        pace_per_week = (weight_to_lose / max(days_remaining, 1)) * 7

        # On track if pace is within 0.5kg/week safe range
        on_track = abs(pace_per_week - target_pace_per_week) <= 0.5

    return {
        "target_weight": goal.weight_target,
        "target_date": goal.target_date.date().isoformat(),
        "current_weight": current_weight,
        "weight_lost": round(weight_lost, 1),
        "pace_per_week": pace_per_week,
        "target_pace_per_week": target_pace_per_week,
        "days_remaining": days_remaining,
        "on_track": on_track,
    }


def _build_trends(db: Session, user_id: int, days: int = 30) -> dict:
    """Build trends section of report."""
    trend = get_weight_trend(db, user_id, days)
    return trend if trend else {}
